### PR TITLE
Add function to run javascript from server

### PR DESCRIPTION
**Pull request by andyquinterom**
This is a simple funciton that allows the user to run javascript from the server. I took my inspiration from the shinyjs package on the R side. This is a feature I pretty much require in every app I build so I thought it would be cool to introduce it.

I placed it as part of the UI module since I belive it makes sense. The javascript runs on the client. However if you disagree there's no problem.

### CODE REVIEW

**Comment by Polkas** [comment]
linked to https://github.com/rstudio/py-shiny/issues/275

**Comment by cpsievert** [comment]
If the intention here is to just execute some JavaScript, that's already possible by providing a `ui.tags.script()` to `ui.insert_ui()`.

**Comment by andyquinterom** [comment]
Could there be significant differences in the way browsers interpret appending script tags rather than directly running some js? I've had issues in the past dealing with insertUI and script tags on different browsers. Could be worth looking into.

**Comment by cpsievert** [comment]
> Could there be significant differences in the way browsers interpret appending script tags rather than directly running some js?

It could be, but I've never encountered this. If you have any hard evidence, please let us know!

> I've had issues in the past dealing with insertUI and script tags

The most recent version of R Shiny actually includes a fix for this exact use case (I'm actually not sure if, in the past, the script would actually execute at all) https://github.com/rstudio/shiny/blame/main/NEWS.md#L17

**Comment by andyquinterom** [comment]
> > Could there be significant differences in the way browsers interpret appending script tags rather than directly running some js?
> 
> It could be, but I've never encountered this. If you have any hard evidence, please let us know!
> 
> > I've had issues in the past dealing with insertUI and script tags
> 
> The most recent version of R Shiny actually includes a fix for this exact use case (I'm actually not sure if, in the past, the script would actually execute at all) https://github.com/rstudio/shiny/blame/main/NEWS.md#L17

This is pretty much it. I do not believe it executed in the past. Since this seems to be it I will leave it as it is. Perhaps developing a separate set or wrappers for such an insertion could be useful to users as mentioned in #275

**Comment by jcheng5** [comment]
@cpsievert IIRC us explicitly supporting `<script>` tags in `insert_ui` makes it difficult for us to ever move on from jQuery if we wanted to, right? (It's already all but impossible on the R side for backwards compatibility reasons, but it's not out of the question for Python)

**Comment by andyquinterom** [comment]
@jcheng5 @cpsievert should we open an issue on this specific topic or continue in this PR?

**Comment by jcheng5** [comment]
Let's continue discussing here, thanks...

**Comment by andyquinterom** [comment]
What components have jquery as a dependencie?

Selectize, datatables, slider, datepicker.

Any others?

**Comment by cpsievert** [comment]
> IIRC us explicitly supporting <script> tags in insert_ui makes it difficult for us to ever move on from jQuery if we wanted to, right?

That might be the case, but I don't know for sure. I could be wrong, but vaguely inserting UI the "vanilla JS" way will execute top-level `<script>` tags, but I don't think it's straightforward to execute child `<script>` tags, which is unfortunate for `input_slider()`, `panel_absolute()`, etc

**Comment by wch** [comment]
In plain JS (not jQuery), if you insert a `<script>` tag by setting a DOM element's `innerHTML`, it will not execute the script. But if you _create_ the tag with `document.createElement('script')`, then it will execute the script.
See https://stackoverflow.com/a/13392818/412655

If we were to drop jQuery and people run JS code by using `insert_ui` with HTML containing `<script>` tags, then on the JS side, we would probably have to do something like: parse the HTML, extract the `<script>` tag, and then insert it with `document.createElement('script')`.

**Comment by wch** [comment]
> What components have jquery as a dependencie?
> 
> Selectize, datatables, slider, datepicker.

One of the challenges for dropping jQuery is that there are a number of third-party Shiny extensions that expect jQuery to be present. (We are currently using the exact same client-side shiny.js code in Python and in R.)

Updating our own code to drop jQuery is doable, but doing it in a way that doesn't break these extensions will be difficult.

**Comment by aghasemi** [comment]
Hi. Does the `tags` method also work for running some JS code _"and getting the result/return value"_?

**Pull request closed without merging**
